version: '3'
services: 
  db:
    build: 
      context: .
      dockerfile: docker/database/Dockerfile
    ports: 
      - "3306:3306"
    volumes: 
      - ./docker/database/db:/docker-entrypoint-initdb.d
      - ./docker/database/db/mysql_data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: go_docker_echo
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes: 
      - ./:/go/src/github.com/kenichi0126/go-docker-echo
    ports: 
      - "8080:8080"
    depends_on:
      - db